name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: docker build -t moeflow-frontend
      - run: docker create moeflow-frontend
        id: create_container
      - run: docker cp ${{ steps.create_container.outputs[0] }}:/moeflow-frontend
